config/routes.rb
Rails.application.routes.draw do

#we call `resources` method and pass it a `Symbol`.
#This instructs Rails to create post routes for creating, updating, viewing, and deleting
#instances of `Post`
resources :topics do
  resources :posts, except: [:index]
end

#modify the `about` route to allow users to visit `/about`, rather than `/welcome/about`
get 'about' => 'welcome#about'

root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all

  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new
    @advertisement.title = params[:advertisement][:title]
    @advertisement.copy = params[:advertisement][:copy]
    @advertisement.price = params[:advertisement][:price]

    if @advertisement.save
      flash[:notice] = "Advertisement was saved"
      redirect_to @advertisement
    else
      flash[:error] = "There was an error saving the advertisement."  
      render :new
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  #   @posts = Post.all
  # end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end


  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])

    @post.topic = @topic

    if @post.save
      flash[:notice] = "Post was saved."
# #36
    redirect_to [@topic, @post]
  else
    flash.now[:alert] = "There was an error saving the post. Please try again."
    render :new
  end
end


  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params.required(:question).permit(:title, :body, :resolved))
    if @question.save
      flash[:notice] = "Question was saved"
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question"
      render :new
    end
  end


  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params.required(:question).permit(:title, :body, :resolved))
      flash[:notice] = "Question was updated"
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted."
      redirect_to questions_path
    else
      flash[:error] = "There was an error deleting question."
      render :show
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new
    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]
    @topic.public = params[:topic][:public]

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]
    @topic.public = params[:topic][:public]

    if @topic.save
       flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def about
  end

  def faq
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/create.html.erb
<h1>Advertisements#create</h1>
<p>Find me in app/views/advertisements/create.html.erb</p>

app/views/advertisements/index.html.erb
<h1>All Ads</h1>


<% @advertisements.each do |ad| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "$#{ad.price}: #{ad.title}", ad%>
      </h4>
    </div>
  </div>
<% end %>

app/views/advertisements/new.html.erb
<h1>Advertisements</h1>

<div class="row">
  <%= form_for @advertisement do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title' %>
  </div>

  <div class="form-group">
    <%= f.label :copy %>
    <%= f.text_area :copy, rows: 8, class: 'form-control', placeholder: 'Enter post' %>
  </div>

  <div class"form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', placeholder: 50 %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/advertisements/show.html.erb
<h1><%="$#{@advertisement.price}: #{@advertisement.title}" %></h1>
<p><%= @advertisement.copy%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccit</title>
    <%= csrf_meta_tags %>

    <!--"viewport meta" tag instructs browsers on cmall, high-pixel density screens(such as retina iphones) to display our pages at a regular, readable size-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Bloccit", root_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtags will get you bannged.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_for [@post.topic, @post] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<!-- iterate over each post in @posts.
For each post we create a link with  post.title as the text that links to /posts/id, with the id from the post.id.
Instance variables created in a controller method are available in its associated view.
Since we create and assign @posts in PostsController#index, we can use it in the posts index view. -->
<% @posts.each do |post| %>
  <!-- <p><%= link_to post.title, post %></p> -->
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to post.title, post %>
      </h4>
    </div>
  </div>      
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @post] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title"%>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </end>
</end>

app/views/posts/show.html.erb
<!-- <h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p> -->

<h1><%= @post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
  </div>
  <div class="col-md-4">


    <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>

    <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions</p>
    <ul>
      <li>Make sure it rhymnes.</li>
      <li>Don't use the letter 'A'.</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
      </div>
      <div class="form-group">
        Mark as Resolved? <%= f.check_box :resolved %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>Questions</h1>
<% @questions.each do |question| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to question.title, question %>
      </h4>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions</p>
    <ul>
      <li>Make sure it rhymnes.</li>
      <li>Don't use the letter 'A'.</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
      </div>
      <div class="form-group">
        <%= f.label :resolved %>
        <%= f.check_box :resolved %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p><% @question.resolved %></p>

<div class="col-md-4">
  <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
  <%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: {confirm: "Do you want to delete this question?"} %>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">

<!-- #11 we pass a block to f.label to generate the HTML for a checkbox-->
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

 <div class="row">
   <div class="col-md-8">

 <!-- #7 we loop over each topic in @topics.-->
     <% @topics.each do |topic| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">

 <!-- #8 we create a link to the show view for each topic.-->
             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">

 <!-- #9 we create a link to create a new topic.-->
     <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>

 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>
 <!-- #10 -->
     <% @topic.posts.each do |post| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to post.title, topic_post_path(@topic, post) %>
           </h4>

           <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago <br>
             <%= post.comments.count %> Comments
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

<button class="social-btn"><%= link_to "Click", "https://news.ycombinator.com/" %></button>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>